### PR TITLE
Fix treegrid sample throwing an error. Fix pinning group hiding forever

### LINKED ISSUE #488: Blazor TreeGrid sample throws an error in dev console
Blazor TreeGrid sample throws error in dev console
https://staging.infragistics.com/blazor-client/

image

Check if there is an issue with xplat sample and its event handlers:
https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/tree-grid/multi-column-headers-template.json

### PR DESCRIPTION
**Pull request by mddragnev**
Fix #488

### CODE REVIEW

File: code-gen-library/WebTreeGridColumnGroupHeaderTemplate/React.tsx [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            </span>
+            <span>{column.header}</span>
+        </div>
+    );
+};
+//end content
+//begin supportingMethods
+public columnGroupStates = new Map<IgrColumn, boolean>();
+public toggleColumnGroup(column: IgrColumn) {
+    const columnGroup = this.grid.contentColumns.find((col) => col.name == column.name) as IgrColumnGroup;
```
Comment (tishko0) [inline code-gen-library/WebTreeGridColumnGroupHeaderTemplate/React.tsx]: this seems to looking up to treeGrid rather than grid

**Review by tishko0 — APPROVED** [review]

**Review by dkamburov — APPROVED** [review]
