### PR TITLE
Add tree grid hide and pin first group templates. Some minor fixes.

### LINKED ISSUE #399: exported WC TreeGrid sample uses EventTemplate with Grid instead of TreeGrid
TreeGrid [xplat sample](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/tree-grid/multi-column-headers-overview.json#L17) sample uses Grid Event Template instead of TreeGrid Event Template which is causing this build error:
image

Solution:
- copy this [event template](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/code-gen-library/WebGridPinFirstGroupToggle/Web.ts) and save it with TreeGrid prefix
- use TreeGrid in the copied template instead of Grid
- update the TreeGrid [xplat sample](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/tree-grid/multi-column-headers-overview.json#L17) sample

### PR DESCRIPTION
**Pull request by skrustev**
Resolves #399

### CODE REVIEW

**Review by HUSSAR-mtrela — APPROVED** [review]

**Comment by HUSSAR-mtrela** [comment]
@skrustev please change convert this draft PR to full PR if ready because we need to have this fix for the critical issue

File: code-gen-library/WebTreeGridHideFirstGroupToggle/Blazor.cs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+//begin imports
+//end imports
+
+public class WebTreeGridHideFirstGroupToggle
+{
+    //begin eventHandler
+    public void WebTreeGridHideFirstGroupToggle(IgbPropertyEditorPropertyDescriptionButtonClickEventArgs args)
+    {
+        var columnGroup = this.grid.ActualColumns[1];
```
Comment (mddragnev) [inline code-gen-library/WebTreeGridHideFirstGroupToggle/Blazor.cs]: this.grid should be either this.treeGrid or a getDescription method to correctly extract the grid instance

File: code-gen-library/WebTreeGridPinFirstGroupToggle/Blazor.cs [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+//begin imports
+//end imports
+
+public class WebTreeGridPinFirstGroupToggle
+{
+    //begin eventHandler
+    public void WebTreeGridPinFirstGroupToggle(IgbPropertyEditorPropertyDescriptionButtonClickEventArgs args)
+    {
+        var columnGroup = this.grid.ActualColumns[1];
```
Comment (mddragnev) [inline code-gen-library/WebTreeGridPinFirstGroupToggle/Blazor.cs]: this.grid should be either this.treeGrid or a getDescription method to correctly extract the grid instance

**Review by mddragnev — CHANGES_REQUESTED** [review]

**Review by mddragnev — APPROVED** [review]
